name: Scott Pobiner
favicon: null
layout_spectrum: 0.9328631442040205
typography_spectrum: 0.6743345293216407
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4565681773237884
  lightness: 0.9303657247219235
  saturation: 0.49633002537302673
  rhythmicContrast: 0.9530077711679041
purpose: []
